# Generated by Django 4.1.1 on 2022-10-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('NIP', models.CharField(max_length=10)),
                ('tanggallahir', models.CharField(max_length=8)),
                ('photo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=30)),
                ('Prodi', models.CharField(max_length=50)),
                ('alamatrumah', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=9)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('NIM', models.CharField(max_length=10)),
                ('tanggallahir', models.CharField(max_length=8)),
                ('photo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=30)),
                ('Prodi', models.CharField(max_length=50)),
                ('alamatrumah', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('NIP', models.CharField(max_length=10)),
                ('tanggallahir', models.CharField(max_length=8)),
                ('photo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=30)),
                ('alamatrumah', models.CharField(max_length=50)),
            ],
        ),
    ]
